/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_haocai_ndktest_NDKFileUtils */

#ifndef _Included_com_haocai_ndktest_NDKFileUtils
#define _Included_com_haocai_ndktest_NDKFileUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_haocai_ndktest_NDKFileUtils
 * Method:    diff
 * Signature: (Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_com_haocai_ndktest_NDKFileUtils_diff
  (JNIEnv *, jclass, jstring ,jstring, jint);

/*
 * Class:     com_haocai_ndktest_NDKFileUtils
 * Method:    patch
 * Signature: (Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_com_haocai_ndktest_NDKFileUtils_patch
  (JNIEnv *, jclass, jstring, jint, jstring);

#ifdef __cplusplus
}
#endif
#endif
